#!/usr/bin/env php
<?php

set_time_limit(0);
require_once __DIR__.'/vendor/autoload.php';

// run app to boot registered services.
$app = require __DIR__ . '/app/bootstrap.php';
require __DIR__.'/app/dev.php';
$app->get('/', function () {return '';});
$app->run();

$console  = new \Pac\Console($app, 'Pac', '0.1');

// some command
$console->add(new \Pac\Command\Check\DaemonCommand());

$console->run();
